### ISSUE TITLE
Image smoothing

### ISSUE THREAD

**Issue by engineeraid-austin** [kmarchais/blender-tpms#2]
When trying to adjust parameters for the lattice pattern, each time I attempt to make a change, I get this pop-up. What's weird is that blender will still render the change. I can move around and pan and what not but it seems to be having a hard time with specifically updating the parameter. 

![image](https://github.com/user-attachments/assets/0e06d6dd-330f-4313-87df-2172dfad11c4)

**Comment by kmarchais** [comment]
Thank you for reporting this. The issue appeared with blender 4.1.
The geometry was still generated but the "Auto Smooth" was not applied.
